import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowRight, ArrowLeft, LockKeyhole, Check, Flag, Star, Crown } from 'lucide-react';
import { worlds, campaignLevel } from '../../shared/progression';
import { getGame } from '../../shared/registry';
import { difficulties } from '../../shared/contracts';
import { usePlayer } from '../stores/player';
import { Landscape } from '../components/Artwork';
import { PageHeading, Modal } from '../components/ui';
export default function Campaign() {
  const { worldId } = useParams(); const world = worlds.find(w => w.id === worldId); const player = usePlayer(); const [selected, setSelected] = useState<number | null>(null);
  const results = player.results.filter(r => r.context?.mode === 'campaign'); const completed = (id: string, n: number) => results.filter(r => r.context?.world === id && r.context.level === n); const count = (id: string) => new Set(results.filter(r => r.context?.world === id).map(r => r.context?.level)).size;
  const selectedLevel = world && selected ? campaignLevel(world.id, selected) : null;
  if (worldId && !world) return <div className="empty-state"><h1>That world is still uncharted.</h1><Link to="/journey">Back to your journey</Link></div>;
  if (world) return <><Link className="text-link back-link" to="/journey"><ArrowLeft size={16}/>All worlds</Link><div className="world-hero panel"><Landscape accent={world.accent}/><PageHeading eyebrow={`${world.category.toUpperCase()} · ${world.levels} CHALLENGES`} title={world.name} description={world.description}/><div className="world-progress"><span>{count(world.id)} / {world.levels} levels complete</span><div className="progress-track"><span style={{ width: `${count(world.id) / world.levels * 100}%`, background: world.accent }}/></div></div></div><div className="section-heading"><h2>Take the next small step</h2><span className="muted">A milestone every 10 levels</span></div><div className="level-grid">{Array.from({ length: world.levels }, (_, i) => { const n = i + 1; const done = completed(world.id, n); const locked = n > 1 && !completed(world.id, n - 1).length; return <button key={n} className={`level-node ${done.length ? 'completed' : ''} ${locked ? 'locked' : 'available'} ${n % 10 === 0 ? 'boss' : ''}`} disabled={locked} onClick={() => setSelected(n)} aria-label={`Level ${n}${locked ? ', locked' : done.length ? ', completed' : ', available'}${n % 10 === 0 ? ', milestone' : ''}`}><span>{locked ? <LockKeyhole size={17}/> : done.length ? <Check size={20}/> : n % 10 === 0 ? <Crown size={22}/> : <Flag size={19}/>}</span><strong>{n}</strong><span className="level-stars">{done.length ? Array.from({ length: Math.max(...done.map(r => r.accuracy >= 95 ? 3 : r.accuracy >= 70 ? 2 : 1)) }, (_, i) => <Star key={i} size={9} fill="currentColor"/>) : <span>· · ·</span>}</span></button>; })}</div><Modal open={selected !== null} onOpenChange={open => { if (!open) setSelected(null); }} title={`${world.name} · Level ${selected}`} description={selectedLevel ? `${getGame(selectedLevel.slug)?.name} · ${difficulties[selectedLevel.difficulty - 1]}` : ''}>{selectedLevel && <><p>Complete this puzzle to take your next step. A new seed makes every level a fresh challenge.</p><Link className="button button-primary full-width mt-6" to={`/games/${selectedLevel.slug}?${new URLSearchParams({ mode: 'campaign', world: world.id, level: String(selected), difficulty: String(selectedLevel.difficulty), seed: selectedLevel.seed })}`}>Enter challenge <ArrowRight size={17}/></Link></>}</Modal></>;
  return <><PageHeading eyebrow="THE MINDFORGE JOURNEY" title="A world of possibilities." description="Ten worlds. Over a thousand small discoveries. A journey you can make your own." action={<span className="date-chip"><Flag size={17}/>{new Set(results.map(r => `${r.context?.world}:${r.context?.level}`)).size} levels explored</span>}/><Link to="/typing/campaign" className="resume-banner typing-entry-banner"><span><Flag size={22}/><strong>Your typing journey</strong><span>Ten new regions · 735 levels · home row to Grandmaster</span></span><ArrowRight size={18}/></Link><div className="worlds-grid">{worlds.map((w, i) => { const available = w.games.every(slug => getGame(slug)); return <article className="world-card panel" key={w.id}><div className="world-landscape"><Landscape accent={w.accent}/><span className="world-number">WORLD {String(i + 1).padStart(2, '0')}</span><span className="world-category" style={{ color: w.accent }}>{w.category}</span></div><div className="world-copy"><h2>{w.name}</h2><p>{w.description}</p><div className="world-meta"><span>{count(w.id)} / {w.levels} levels</span><span>{Math.round(count(w.id) / w.levels * 100)}%</span></div><div className="progress-track"><span style={{ width: `${count(w.id) / w.levels * 100}%`, background: w.accent }}/></div>{available ? <Link className="text-link" to={`/campaign/${w.id}`}>{count(w.id) ? 'Continue exploring' : 'Enter this world'}<ArrowRight size={16}/></Link> : <p className="small-note">This world opens with the next game collection.</p>}</div></article>; })}</div></>;
}
