import { useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { Search, LayoutGrid } from 'lucide-react';
import { games } from '../../shared/registry';
import { categories } from '../../shared/contracts';
import GameCard from '../components/GameCard';
import { EmptyState, PageHeading } from '../components/ui';
import { usePlayer } from '../stores/player';
export default function Games() {
  const [params, setParams] = useSearchParams(); const query = params.get('q') || ''; const category = params.get('category') || 'All'; const [filter, setFilter] = useState('all'); const [duration, setDuration] = useState('any'); const player = usePlayer();
  const filtered = games.filter(g => (category === 'All' || g.category === category) && `${g.name} ${g.description} ${g.category}`.toLowerCase().includes(query.toLowerCase()) && (duration === 'any' || g.duration <= Number(duration)) && (filter !== 'favorites' || player.favorites.includes(g.slug)) && (filter !== 'recent' || player.results.some(r => r.slug === g.slug)));
  return <><PageHeading eyebrow="MAKE ROOM FOR CURIOSITY" title="Your mind’s playground." description={`${games.length} ways to find your focus, challenge your thinking, and enjoy a little discovery.`}/><div className="library-toolbar"><div className="search-field"><Search size={19}/><input aria-label="Search games" placeholder="Find a game, skill, or a little inspiration…" value={query} onChange={e => setParams(p => { p.set('q', e.target.value); return p; }, { replace: true })}/></div><select aria-label="Game collection" value={filter} onChange={e => setFilter(e.target.value)}><option value="all">All games</option><option value="favorites">My favorites</option><option value="recent">Recently played</option></select><select aria-label="Play time" value={duration} onChange={e => setDuration(e.target.value)}><option value="any">Any duration</option><option value="3">Under 3 minutes</option><option value="5">Under 5 minutes</option></select></div><div className="filter-tabs" aria-label="Game categories">{['All', ...categories.filter(c => games.some(g => g.category === c))].map(c => <button key={c} className={category === c ? 'selected' : ''} aria-pressed={category === c} onClick={() => setParams(p => { p.set('category', c); return p; }, { replace: true })}>{c}{c === 'All' && <span>{games.length}</span>}</button>)}</div><div className="section-heading"><h2>{category === 'All' ? 'A challenge for every kind of mind' : `${category} games`}</h2><span className="muted">{filtered.length} games</span></div>{filtered.length ? <div className="games-grid">{filtered.map(game => <GameCard key={game.slug} game={game}/>)}</div> : <EmptyState icon={<LayoutGrid size={30}/>} title="A little room for discovery" description="Try another search or collection. Tap a heart on a game to save it to your favorites."/>}</>;
}
