import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { Trophy, Users, ArrowRight, RefreshCw, Copy, Check, UserPlus } from 'lucide-react';
import { api } from '../lib/api';
import { usePlayerStore } from '../stores/player';
import { games } from '../../shared/registry';
import { Button, EmptyState, PageHeading } from '../components/ui';
interface Leader { userId: string; username: string; score: number; games: number; }
interface Friend { id: string; requesterId: string; recipientId: string; status: string; username: string; }
export default function Social({ friends = false }: { friends?: boolean }) {
  const account = usePlayerStore(s => s.account); const setToast = usePlayerStore(s => s.setToast); const [period, setPeriod] = useState('weekly'); const [slug, setSlug] = useState('memory-cards'); const [username, setUsername] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const board = useQuery({ queryKey: ['leaderboard', period, slug, account?.id], queryFn: () => api<Leader[]>(`/leaderboards?period=${period}&slug=${slug}`), enabled: !friends });
  const people = useQuery({ queryKey: ['friends', account?.id], queryFn: () => api<Friend[]>('/friends'), enabled: friends && Boolean(account) });
  async function request() { setError(''); setBusy(true); try { await api('/friends', { method: 'POST', body: JSON.stringify({ username: username.trim() }) }); setUsername(''); await people.refetch(); setToast('Friend request sent.'); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to send request.'); } finally { setBusy(false); } }
  async function share() { const url = `${window.location.origin}/games/${slug}?seed=${encodeURIComponent(`friends:${crypto.randomUUID()}`)}&difficulty=3`; try { await navigator.clipboard.writeText(url); setToast('Puzzle link copied. Anyone with the link can play the same puzzle.'); } catch { setError(`Copy this puzzle link: ${url}`); } }
  if (friends) return <><Link to="/typing/leaderboards" className="resume-banner typing-entry-banner"><span><strong>Typing Academy rankings & races</strong><span>Compare accurate typing with friends and players around the world</span></span>→</Link><PageHeading eyebrow="A LITTLE FRIENDLY MOTIVATION" title="Better with a curious friend." description="Share a puzzle and compare your results together, at your own pace."/><section className="panel share-puzzle"><span className="achievement-emblem"><Users size={35}/></span><div><h2>Same puzzle. Two perspectives.</h2><p>Create a link to a shared puzzle. Your friend gets the same layout and difficulty, with their own timer.</p><div className="button-row"><select aria-label="Game to share" value={slug} onChange={e => setSlug(e.target.value)}>{games.map(g => <option key={g.slug} value={g.slug}>{g.name}</option>)}</select><Button onClick={() => void share()}><Copy size={16}/>Copy puzzle link</Button></div><p className="small-note">Shared puzzles are asynchronous practice. Live typing races are available in Typing Academy.</p></div></section>{!account ? <EmptyState icon={<UserPlus size={30}/>} title="Make a little room for connection." description="Sign in to send friend requests and grow your circle. You can share puzzle links as a guest." to="/profile" label="Sign in or create account"/> : <section className="panel friends-panel"><h2>Your circle</h2><form className="button-row" onSubmit={e => { e.preventDefault(); void request(); }}><input aria-label="Friend username" placeholder="Enter a friend’s exact username" required value={username} onChange={e => setUsername(e.target.value)}/><Button disabled={busy}><UserPlus size={17}/>Send request</Button></form>{people.isPending && <p role="status">Loading your friends…</p>}{people.error && <p className="error" role="alert">{people.error.message}<Button variant="ghost" onClick={() => void people.refetch()}>Try again</Button></p>}{people.data?.length === 0 && <p className="muted">No friends yet. Send a request to someone you know.</p>}{people.data?.map(person => <div className="friend-row" key={person.id}><span className="avatar">{person.username[0]?.toUpperCase()}</span><strong>{person.username}</strong><span>{person.status === 'accepted' ? 'Friends' : person.requesterId === account.id ? 'Request sent' : 'Wants to connect'}</span>{person.status === 'pending' && person.recipientId === account.id && <Button variant="secondary" onClick={() => { void api(`/friends/${person.id}/accept`, { method: 'POST' }).then(() => people.refetch()).catch(e => setError(e.message)); }}><Check size={16}/>Accept</Button>}</div>)}</section>}{error && <p role="alert" className="error break-word">{error}</p>}</>;
  return <><Link to="/typing/leaderboards" className="resume-banner typing-entry-banner"><span><strong>Typing Academy rankings</strong><span>Daily WPM, accuracy, CodeType, and friends</span></span>→</Link><PageHeading eyebrow="CURIOSITY LOVES COMPANY" title="A little friendly competition." description="Real players. Verified scores. Choose a game and find your next personal best."/><div className="leaderboard-toolbar"><div className="filter-tabs">{['daily', 'weekly', 'monthly', 'all'].map(p => <button className={p === period ? 'selected' : ''} key={p} aria-pressed={p === period} onClick={() => setPeriod(p)}>{p === 'all' ? 'All time' : p[0].toUpperCase() + p.slice(1)}</button>)}</div><select aria-label="Leaderboard game" value={slug} onChange={e => setSlug(e.target.value)}>{games.map(g => <option key={g.slug} value={g.slug}>{g.name}</option>)}</select></div><div className="panel leaderboard-panel"><div className="leaderboard-heading"><Trophy size={28}/><div><h2>{games.find(g => g.slug === slug)?.name}</h2><p>Highest verified score per public player</p></div><Button variant="ghost" aria-label="Refresh leaderboard" onClick={() => void board.refetch()}><RefreshCw size={18}/></Button></div>{board.isPending ? <div className="page-loading" role="status">Loading verified scores…</div> : board.error ? <EmptyState icon={<Trophy size={29}/>} title="The leaderboard is taking a breather." description={board.error.message}/> : !board.data?.length ? <EmptyState icon={<Trophy size={29}/>} title="There’s room to be the first." description="No public verified scores for this game and period yet. Play with an account and choose a public profile to take part." to={`/games/${slug}`} label="Play this challenge"/> : <div className="table-wrap"><table><thead><tr><th>Rank</th><th>Explorer</th><th>Best score</th><th>Games played</th></tr></thead><tbody>{board.data.map((row, i) => <tr key={row.userId} className={row.userId === account?.id ? 'my-rank' : ''}><td>{i + 1}</td><td>{row.username}{row.userId === account?.id ? ' (you)' : ''}</td><td>{row.score.toLocaleString()}</td><td>{row.games}</td></tr>)}</tbody></table></div>}</div><div className="leaderboard-note"><ShieldNote/><p>Only account games validated by the service appear here. Local practice stays in your own statistics. <Link to="/settings">Manage your privacy <ArrowRight size={13}/></Link></p></div></>;
}
function ShieldNote() { return <Check size={20}/>; }
