import { Link } from 'react-router-dom';
import { useEffect, useState } from 'react';
import { ArrowRight, Check, Clock3, Dumbbell, Flame, Sparkles, Trophy } from 'lucide-react';
import { PageHeading, Button } from '../components/ui';
import { GameArtwork, categoryIcons, categoryColors } from '../components/Artwork';
import { usePlayer, usePlayerStore } from '../stores/player';
import { generateWorkout } from '../../shared/workout';
import { dailyChallenge } from '../../shared/daily';
import { getGame } from '../../shared/registry';
import { utcDate } from '../../shared/progression';
import { difficulties } from '../../shared/contracts';
function Countdown() { const [now, setNow] = useState(Date.now()); useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(timer); }, []); const left = 86400 - Math.floor(now / 1000) % 86400; return <span>{Math.floor(left / 3600).toString().padStart(2, '0')}:{Math.floor(left % 3600 / 60).toString().padStart(2, '0')}:{(left % 60).toString().padStart(2, '0')}</span>; }
export default function Workout({ daily = false }: { daily?: boolean }) {
  const player = usePlayer(); const update = usePlayerStore(s => s.update); const date = utcDate(); const workout = generateWorkout(player.results, player.workoutMinutes, date);
  const completed = (seed: string) => player.results.some(r => r.seed === seed && r.context?.date === date && r.context?.mode === 'workout');
  const done = workout.filter(g => completed(g.seed)).length; const next = workout.find(g => !completed(g.seed)); const challenge = dailyChallenge(); const game = getGame(challenge.slug)!; const dailyResults = player.results.filter(r => r.context?.mode === 'daily' && r.context.date === date);
  const link = (g: typeof workout[number]) => `/games/${g.slug}?${new URLSearchParams({ mode: 'workout', seed: g.seed, difficulty: String(g.difficulty), date })}`;
  if (daily) return <><PageHeading eyebrow="A SHARED MOMENT OF DISCOVERY" title="One day. One challenge." description="The same puzzle for every player. A fresh perspective every midnight, UTC." action={<span className="date-chip"><Clock3 size={16}/>Next puzzle in <Countdown/></span>}/><div className="daily-detail panel"><GameArtwork slug={game.slug} category={game.category}/><div className="daily-detail-copy"><span className="eyebrow"><Flame size={15}/> TODAY’S CHALLENGE · {date}</span><h2>{game.name}</h2><p>{game.description}</p><div className="detail-tags"><span>{game.category}</span><span>{difficulties[challenge.difficulty - 1]}</span><span>~{game.duration} min</span></div><Link className="button button-primary" to={`/games/${game.slug}?${new URLSearchParams({ mode: 'daily', seed: challenge.seed, difficulty: String(challenge.difficulty), date })}`}>{dailyResults.length ? 'Play again' : 'Take the challenge'}<ArrowRight size={17}/></Link>{dailyResults.length > 0 && <p className="success"><Check size={17}/>Completed · Your best: {Math.max(...dailyResults.map(r => r.score))} points</p>}</div></div><div className="info-grid"><div className="panel info-card"><TargetIcon/><h3>Your own best is a worthy opponent.</h3><p>Play as often as you like and watch your personal score develop. Account scores are checked by the game service.</p></div><div className="panel info-card"><Trophy size={25}/><h3>A little friendly motivation</h3><p>Discover the leaderboard and choose whether your account profile is public.</p><Link className="text-link" to="/leaderboards">View leaderboards <ArrowRight size={15}/></Link></div></div></>;
  return <><PageHeading eyebrow="A SMALL COMMITMENT TO YOURSELF" title="Your daily brain workout." description="A balanced mix of mental challenges, with difficulty that follows your progress." action={<select aria-label="Workout duration" value={player.workoutMinutes} onChange={e => update({ workoutMinutes: Number(e.target.value) })}><option value={5}>5-minute reset</option><option value={10}>10-minute workout</option><option value={15}>15-minute deep dive</option></select>}/><div className="workout-summary panel"><div className="workout-emblem"><Dumbbell size={37}/></div><div><span className="eyebrow">YOUR DAILY MOMENT</span><h2>{done === workout.length ? 'You made time for your mind.' : 'A little focus goes a long way.'}</h2><p>{workout.length} games · About {player.workoutMinutes} minutes · Adaptive difficulty</p></div><div className="workout-count"><strong>{done}<span>/{workout.length}</span></strong><small>completed</small></div></div><div className="workout-layout"><div className="workout-list">{workout.map((item, i) => { const game = getGame(item.slug)!; const Icon = categoryIcons[game.category]; const finished = completed(item.seed); return <Link className={`workout-item panel ${finished ? 'complete' : ''}`} key={item.seed} to={link(item)}><span className="workout-number">{finished ? <Check size={20}/> : String(i + 1).padStart(2, '0')}</span><span className="stat-icon" style={{ color: categoryColors[game.category], background: `${categoryColors[game.category]}15` }}><Icon size={24}/></span><span className="workout-item-copy"><small>{game.category} · {difficulties[item.difficulty - 1]}</small><strong>{game.name}</strong><span>{game.description}</span></span><span className="workout-status">{finished ? 'Completed' : `~${game.duration} min`}<ArrowRight size={18}/></span></Link>; })}</div><aside className="panel workout-aside"><Sparkles size={26}/><h3>{done === workout.length ? 'That’s a wrap.' : 'Built around your rhythm.'}</h3><p>{done === workout.length ? 'Every puzzle is a little investment in your day. Come back tomorrow for a fresh mix, or explore another challenge.' : 'Your recent accuracy and pace help set each game’s difficulty. Take breaks whenever you need — your progress stays right here.'}</p><div className="progress-track"><span style={{ width: `${done / workout.length * 100}%` }}/></div><p className="small-note">{done} of {workout.length} complete today</p>{next ? <Link to={link(next)} className="button button-primary full-width">{done ? 'Continue workout' : 'Begin workout'}<ArrowRight size={16}/></Link> : <Link to="/daily" className="button button-primary full-width">Try the daily challenge<ArrowRight size={16}/></Link>}<Button variant="ghost" onClick={() => { update({ onboarded: true }); usePlayerStore.getState().setToast('Your workout is saved automatically after each completed puzzle.'); }}>How is progress saved?</Button></aside></div></>;
}
function TargetIcon() { return <Sparkles size={25}/>; }
