import type { ButtonHTMLAttributes, ReactNode } from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import * as AlertDialog from '@radix-ui/react-alert-dialog';
import * as Switch from '@radix-ui/react-switch';
import { ArrowRight, X } from 'lucide-react';
import { Link } from 'react-router-dom';
import { cn } from '../lib/utils';
export function DeletionDialog({ open, onOpenChange, title, description, children }: { open: boolean; onOpenChange: (open: boolean) => void; title: string; description: string; children: ReactNode }) {
  return <AlertDialog.Root open={open} onOpenChange={onOpenChange}><AlertDialog.Portal><AlertDialog.Overlay className="modal-overlay"/><AlertDialog.Content className="modal-content"><AlertDialog.Title className="modal-title">{title}</AlertDialog.Title><AlertDialog.Description className="modal-description">{description}</AlertDialog.Description>{children}<AlertDialog.Cancel asChild><Button variant="secondary" className="mt-6">Keep my progress</Button></AlertDialog.Cancel></AlertDialog.Content></AlertDialog.Portal></AlertDialog.Root>;
}
export function Button({ className, variant = 'primary', ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'primary' | 'secondary' | 'ghost' | 'danger' }) { return <button className={cn('button', `button-${variant}`, className)} {...props}/>; }
export function ActionLink({ to, children, className }: { to: string; children: ReactNode; className?: string }) { return <Link className={cn('button button-primary', className)} to={to}>{children}<ArrowRight size={17}/></Link>; }
export function Modal({ open, onOpenChange, title, description, children }: { open: boolean; onOpenChange: (open: boolean) => void; title: string; description?: string; children: ReactNode }) { return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="modal-overlay"/><Dialog.Content className="modal-content"><Dialog.Title className="modal-title">{title}</Dialog.Title><Dialog.Description className="modal-description">{description}</Dialog.Description><Dialog.Close className="icon-button modal-close" aria-label="Close dialog"><X size={19}/></Dialog.Close>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>; }
export function Confirm({ children, title, description, onConfirm }: { children: ReactNode; title: string; description: string; onConfirm: () => void }) { return <AlertDialog.Root><AlertDialog.Trigger asChild>{children}</AlertDialog.Trigger><AlertDialog.Portal><AlertDialog.Overlay className="modal-overlay"/><AlertDialog.Content className="modal-content"><AlertDialog.Title className="modal-title">{title}</AlertDialog.Title><AlertDialog.Description className="modal-description">{description}</AlertDialog.Description><div className="button-row mt-6"><AlertDialog.Cancel asChild><Button variant="secondary">Keep my progress</Button></AlertDialog.Cancel><AlertDialog.Action asChild><Button variant="danger" onClick={onConfirm}>Delete permanently</Button></AlertDialog.Action></div></AlertDialog.Content></AlertDialog.Portal></AlertDialog.Root>; }
export function Toggle({ label, description, checked, onChange }: { label: string; description?: string; checked: boolean; onChange: (value: boolean) => void }) { const id = label.replaceAll(' ', '-').toLowerCase(); return <div className="setting-row"><div><label htmlFor={id}>{label}</label>{description && <p>{description}</p>}</div><Switch.Root id={id} className="switch" checked={checked} onCheckedChange={onChange}><Switch.Thumb className="switch-thumb"/></Switch.Root></div>; }
export function PageHeading({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description?: string; action?: ReactNode }) { return <div className="page-heading"><div>{eyebrow && <div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1>{description && <p>{description}</p>}</div>{action}</div>; }
export function SectionHeading({ title, detail, to, label = 'View all' }: { title: string; detail?: string; to?: string; label?: string }) { return <div className="section-heading"><div><h2>{title}</h2>{detail && <p>{detail}</p>}</div>{to && <Link to={to} className="text-link">{label}<ArrowRight size={15}/></Link>}</div>; }
export function EmptyState({ icon, title, description, to, label }: { icon: ReactNode; title: string; description: string; to?: string; label?: string }) { return <div className="empty-state"><span className="empty-icon">{icon}</span><h3>{title}</h3><p>{description}</p>{to && <ActionLink to={to}>{label || 'Explore games'}</ActionLink>}</div>; }
