import type { GameDefinition } from './contracts';

export const puzzleGames: GameDefinition[] = [
  { slug: 'memory-cards', name: 'Memory Cards', category: 'Memory', description: 'A little focus. A perfect match. Find every hidden pair.', duration: 3, icon: 'Layers', accent: '#b79aff', tutorial: ['Turn over two cards to look for matching symbols.', 'A matching pair stays face up. Different symbols turn back over after a moment.', 'Remember each position and find all the pairs. Use Tab and Enter to play with a keyboard.', 'Higher difficulties add more cards, from 4 to 48. Fewer mismatches improve your accuracy.'] },
  { slug: 'sequence-recall', name: 'Sequence Recall', category: 'Memory', description: 'Watch the rhythm, hold the pattern, make it your own.', duration: 3, icon: 'Grid3X3', accent: '#83aaff', tutorial: ['Watch the numbered tiles light up, one at a time.', 'When “Your turn” appears, repeat the tiles in exactly the same order.', 'Each successful round adds another step. A mistake replays the current sequence.', 'Complete every round before making three mistakes. Pausing safely restarts the preview.'] },
  { slug: 'sudoku', name: 'Sudoku', category: 'Logic', description: 'Find your flow, one beautifully logical number at a time.', duration: 8, icon: 'Grid2X2', accent: '#8edbb5', tutorial: ['Fill each empty cell so every row, column and outlined box contains each number exactly once.', 'Choose a cell, then choose a number or type it. Backspace clears an editable cell.', 'Fixed clues cannot be changed. A coral number marks an incorrect entry; choose another number to correct it.', 'Beginner and Easy use 4×4, Normal and Challenging use 6×6, and higher levels use 9×9. Every generated puzzle has exactly one solution.'] },
  { slug: 'mental-math', name: 'Mental Math Rush', category: 'Math', description: 'Quick calculations. Clear thinking. Meet your next challenge.', duration: 2, icon: 'Calculator', accent: '#ffc581', tutorial: ['Solve the equation, type a whole-number answer, then press Enter or Check answer.', 'Each answer moves to the next calculation. The previous answer is shown below the equation.', 'Higher difficulties introduce multiplication, division, percentages and fractions of whole numbers.', 'The questions become harder during the session. Get at least half right to complete the challenge.'] },
  { slug: 'maze-runner', name: 'Maze Runner', category: 'Spatial', description: 'Find a way through a fresh maze of possibilities.', duration: 4, icon: 'Route', accent: '#7bcfd6', tutorial: ['Move the glowing player to the flag at the maze exit.', 'Use the direction buttons, arrow keys, or W, A, S and D. Your trail shows where you have been.', 'Walls block your movement. Find a route through the open corridors.', 'Every maze has a route to the exit. Higher difficulty gives you a larger maze; fewer moves improve efficiency.'] },
  { slug: 'sokoban', name: 'Sokoban', category: 'Strategy', description: 'Think a few steps ahead. Put every piece in its place.', duration: 6, icon: 'Box', accent: '#dca5e3', tutorial: ['Push each crate onto a circular target. You can push one crate at a time.', 'Walk with the direction buttons, arrow keys, or W, A, S and D.', 'You cannot pull crates. Think ahead: a crate pushed into a corner may become stuck.', 'Undo reverses your last step and Reset restores the puzzle. Every starting position is generated from a solved board and validated.'] },
  { slug: 'stroop-challenge', name: 'Stroop Challenge', category: 'Focus', description: 'Read between the colors. Give your attention a workout.', duration: 2, icon: 'Palette', accent: '#f18faa', tutorial: ['Choose the color of the ink, even when the word names a different color.', 'For example, if BLUE appears in coral ink, choose Coral.', 'Use the labeled color buttons or the matching number keys. The screen-reader description names both the word and ink.', 'Higher levels add more colors and more rounds. Get at least half right to complete the challenge.'] },
  { slug: 'pattern-matrix', name: 'Pattern Matrix', category: 'Patterns', description: 'Spot the quiet logic connecting the bigger picture.', duration: 4, icon: 'Shapes', accent: '#d1cd85', tutorial: ['Study the 3×3 matrix and choose the tile that belongs in the empty corner.', 'Look across each row and down each column. The same transformation repeats in both directions.', 'Dots cycle from 1 to 4, the pointer can turn clockwise, and outlines can cycle circle → square → diamond → hexagon.', 'Higher levels combine these rules. A wrong option is crossed out so you can reason through the remaining choices.'] },
];

export const typingGame: GameDefinition = { slug: 'typing-academy', name: 'Typing Academy', category: 'Typing', description: 'Build accuracy, find your rhythm, and master the keyboard.', duration: 2, icon: 'Keyboard', accent: '#a8d4db', tutorial: ['Focus the exercise field to begin typing.', 'Follow the highlighted character and recommended finger.', 'Prioritize accuracy. Your results build keyboard mastery and MindForge XP.'] };
export const games: GameDefinition[] = [...puzzleGames, typingGame];
export function getGame(slug: string): GameDefinition | undefined { return games.find(game => game.slug === slug); }
